In [1]:
versioninfo()

Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores


## 2-7. 型の基本

### 2-7-1. プリミティブ型

#### プリミティブ整数型

#### コード2-91. `Int`/`UInt` の確認

In [2]:
Int

Int64

In [3]:
UInt

UInt64

#### コード2-92. 整数リテラルの型の確認

In [4]:
typeof(1)

Int64

In [5]:
typeof(2147483647)

Int64

In [6]:
typeof(2147483648)

Int64

In [7]:
typeof(9223372036854775807)

Int64

In [8]:
typeof(9223372036854775808)

Int128

In [9]:
typeof(170141183460469231731687303715884105727)

Int128

In [10]:
typeof(170141183460469231731687303715884105728)

BigInt

In [11]:
typeof(0x0) == typeof(0xff) == 
typeof(0o0) == typeof(0o377) == 
typeof(0b0) == typeof(0b11111111) == UInt8

true

In [12]:
typeof(0x000) == typeof(0xffff) == 
typeof(0o400) == typeof(0o177777) == 
typeof(0b000000000) == typeof(0b1111111111111111) == UInt16

true

In [13]:
typeof(0x00000) == typeof(0xffffffff) == 
typeof(0o200000) == typeof(0o37777777777) == 
typeof(0b00000000000000000) == 
typeof(0b11111111111111111111111111111111) == UInt32

true

In [14]:
# 以降煩雑になるので16進表記リテラルのみ示す
typeof(0x000000000) == typeof(0xffffffffffffffff) == UInt64

true

In [15]:
typeof(0x00000000000000000) == 
typeof(0xffffffffffffffffffffffffffffffff) == UInt128

true

In [16]:
typeof(0x000000000000000000000000000000000) == 
typeof(0x100000000000000000000000000000000) == BigInt

true

#### コード2-93. 整数（リテラル）の型変換例

In [17]:
Int8(1)
# REPL の見た目上は区別が付かない

1

In [18]:
typeof(Int8(1))

Int8

In [19]:
Int8(257)

LoadError: InexactError: trunc(Int8, 257)

In [20]:
257 % Int8  # こちらはエラーにならない

1

In [21]:
typeof(257 % Int8)

Int8

In [22]:
UInt16(4660)

0x1234

In [23]:
4660 % UInt16

0x1234

In [24]:
typeof(UInt16(4660)) == typeof(4660 % UInt16) == UInt16

true

#### プリミティブ浮動小数点数型

#### コード2-94. 浮動小数点数（リテラル）の型の確認と型変換例

In [25]:
typeof(1.0)

Float64

In [26]:
typeof(1e0)

Float64

In [27]:
typeof(1f0)

Float32

In [28]:
typeof(0x1p0)

Float64

In [29]:
Float16(1)

Float16(1.0)

In [30]:
Float32(1.0)

1.0f0

In [31]:
Float16(65535)  # 65535 > floatmax(Float16) == 65504.0

Inf16

#### その他の標準プリミティブ型

### 2-7-2. 複合型

#### コード2-95. 複合型の例(1)：簡単な定義例

In [32]:
struct Point
    x
    y
end

In [33]:
pt = Point(1.0, 2.0)

Point(1.0, 2.0)

In [34]:
pt.x

1.0

In [35]:
pt.y

2.0

#### コード2-96. 複合型の例(2)：有理数と複素数のフィールド

In [36]:
r = 1//2

1//2

In [37]:
r.num

1

In [38]:
r.den

2

In [39]:
c = 1.0 + 2.0im

1.0 + 2.0im

In [40]:
c.re

1.0

In [41]:
c.im

2.0

#### コード2-97. 有理数と複素数のフィールドと同じ値を返す関数

In [42]:
numerator(r)

1

In [43]:
denominator(r)

2

In [44]:
numerator(2)

2

In [45]:
denominator(2)

1

In [46]:
real(c)

1.0

In [47]:
imag(c)

2.0

In [48]:
real(2.0)

2.0

In [49]:
imag(2.0)

0.0

### 2-7-3. コレクション型

#### 配列

##### コード2-98. 配列の型の確認

In [50]:
typeof([1, 2, 3])

Vector{Int64} (alias for Array{Int64, 1})

In [51]:
typeof([1.0 2.0; 3.0 4.0; 5.0 6.0])

Matrix{Float64} (alias for Array{Float64, 2})

In [52]:
typeof([100x + 10y + z for x=1:4, y=1:5, z=1:3])

Array{Int64, 3}

##### コード2-99. インデクシング(1)：ベクトルのインデクシング参照

In [53]:
v = [1, 2, 3];

In [54]:
v[1]

1

In [55]:
v[2]

2

In [56]:
v[0]　　# v[-1], v[4] 等も同様

LoadError: BoundsError: attempt to access 3-element Vector{Int64} at index [0]

In [57]:
v[begin]

1

In [58]:
v[end]

3

In [59]:
v[end-1]

2

##### コード2-100. インデクシング(2)：ベクトルのインデクシング代入

In [60]:
v[2] = 0

0

In [61]:
v

3-element Vector{Int64}:
 1
 0
 3

In [62]:
v[4] = 99

LoadError: BoundsError: attempt to access 3-element Vector{Int64} at index [4]

##### コード2-101. インデクシング(3)：行列（多次元配列）のインデクシング（多次元インデックス）

In [63]:
M = [1.0 2.0; 3.0 4.0; 5.0 6.0];

In [64]:
M[1, 1]

1.0

In [65]:
M[3, 2]

6.0

In [66]:
M[CartesianIndex(3, 2)]

6.0

In [67]:
M[2, 3]

LoadError: BoundsError: attempt to access 3×2 Matrix{Float64} at index [2, 3]

In [68]:
M[begin, begin]

1.0

In [69]:
M[end, end]

6.0

In [70]:
M[2, 2] = 0.0

0.0

In [71]:
M

3×2 Matrix{Float64}:
 1.0  2.0
 3.0  0.0
 5.0  6.0

In [72]:
M[CartesianIndex(2, 2)] = 10.0

10.0

In [73]:
M

3×2 Matrix{Float64}:
 1.0   2.0
 3.0  10.0
 5.0   6.0

##### コード2-102. インデクシング(4)：行列（多次元配列）のインデクシング（線形インデックス）

In [74]:
M = [1.0 2.0; 3.0 4.0; 5.0 6.0]

3×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0
 5.0  6.0

In [75]:
M[1]

1.0

In [76]:
M[2]

3.0

In [77]:
M[3]

5.0

In [78]:
M[4]

2.0

In [79]:
M[5]

4.0

In [80]:
M[6]

6.0

##### コード2-103. インデクシング(5)：範囲指定

In [81]:
v = [1, 0, 3]

3-element Vector{Int64}:
 1
 0
 3

In [82]:
v[1:2]

2-element Vector{Int64}:
 1
 0

In [83]:
M = [1.0 2.0; 3.0 4.0; 5.0 6.0]

3×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0
 5.0  6.0

In [84]:
M[1:2, 1]

2-element Vector{Float64}:
 1.0
 3.0

In [85]:
M[1, :]

2-element Vector{Float64}:
 1.0
 2.0

In [86]:
M[1:1, :]

1×2 Matrix{Float64}:
 1.0  2.0

In [87]:
M[1:2, 1:1]

2×1 Matrix{Float64}:
 1.0
 3.0

##### コード2-104. インデクシング(6)：論理式によるフィルタリング

In [88]:
M[M .> 3]

3-element Vector{Float64}:
 5.0
 4.0
 6.0

#### 辞書

##### コード2-105. 辞書の例(1)：定義とキー参照

In [89]:
d = Dict(:a => 1, :b => 2, :c => 3)

Dict{Symbol, Int64} with 3 entries:
  :a => 1
  :b => 2
  :c => 3

In [90]:
d[:a]

1

In [91]:
d[:n]

LoadError: KeyError: key :n not found

##### コード2-106. 辞書の例(2)：エントリーの登録と更新

In [92]:
d[:b] = 20  # エントリーの更新

20

In [93]:
d[:e] = 5  # エントリーの登録

5

In [94]:
d

Dict{Symbol, Int64} with 4 entries:
  :a => 1
  :b => 20
  :e => 5
  :c => 3

##### コード2-107. 辞書の例(3)：キーと値の型（エラー例）

In [95]:
d[:pi] = π

LoadError: MethodError: no method matching Int64(::Irrational{:π})
Closest candidates are:
  (::Type{T})(::T) where T<:Number at boot.jl:772
  (::Type{T})(::AbstractChar) where T<:Union{Int32, Int64} at char.jl:51
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
  ...

In [96]:
d["Invarid Key"] = -1

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Symbol
Closest candidates are:
  convert(::Type{T}, ::T) where T at Base.jl:61
  Symbol(::String) at boot.jl:489
  Symbol(::AbstractString) at strings/basic.jl:228
  ...

#### 集合

##### コード2-108. 集合の例(1)：定義

In [97]:
s = Set([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

Set{Int64} with 7 elements:
  5
  4
  6
  2
  9
  3
  1

##### コード2-109. 集合の例(2)：イテレーション、`in` 演算子

In [98]:
for n in s
    println(n)
end

5
4
6
2
9
3
1


In [99]:
3 ∈ s

true

In [100]:
0 ∉ s

true

##### コード2-110. 集合の例(3)：要素の追加と削除

In [101]:
push!(s, 0)

Set{Int64} with 8 elements:
  5
  4
  6
  0
  2
  9
  3
  1

In [102]:
push!(s, 9)

Set{Int64} with 8 elements:
  5
  4
  6
  0
  2
  9
  3
  1

In [103]:
pop!(s, 0)

0

In [104]:
s

Set{Int64} with 7 elements:
  5
  4
  6
  2
  9
  3
  1

#### タプル/名前付きタプル

##### コード2-111. タプルの例（定義・インデクシング参照）

In [105]:
t = ('a', 2, 99.9, π)

('a', 2, 99.9, π)

In [106]:
t[1]

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [107]:
t[4]

π = 3.1415926535897...

In [108]:
t[3] = 10.0

LoadError: MethodError: no method matching setindex!(::Tuple{Char, Int64, Float64, Irrational{:π}}, ::Float64, ::Int64)

In [109]:
push!(t, "Not Available")

LoadError: MethodError: no method matching push!(::Tuple{Char, Int64, Float64, Irrational{:π}}, ::String)
Closest candidates are:
  push!(::Any, ::Any, ::Any) at abstractarray.jl:3059
  push!(::Any, ::Any, ::Any, ::Any...) at abstractarray.jl:3060
  push!(::Base.InvasiveLinkedList{Base.LinkedListItem{T}}, ::T) where T at linked_list.jl:138
  ...

##### コード2-112. 名前付きタプルの例（定義・インデクシング参照・キー参照・プロパティ参照）

In [110]:
nt = (c='a', i=2, f=99.9, pi=π)

(c = 'a', i = 2, f = 99.9, pi = π)

In [111]:
nt.c

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [112]:
nt[:i]

2

In [113]:
nt[3]

99.9

In [114]:
nt.notexists

LoadError: type NamedTuple has no field notexists

In [115]:
nt.f = 10.0

LoadError: setfield!: immutable struct of type NamedTuple cannot be changed

In [116]:
nt[:notexists] = "New Value"

LoadError: MethodError: no method matching setindex!(::NamedTuple{(:c, :i, :f, :pi), Tuple{Char, Int64, Float64, Irrational{:π}}}, ::String, ::Symbol)

### 2-7-4. 文字列型

#### コード2-113. 文字列型の例

In [117]:
str = "abcあいう😄漢字"

"abcあいう😄漢字"

In [118]:
str[1]

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [119]:
str[4]

'あ': Unicode U+3042 (category Lo: Letter, other)

In [120]:
str[7]

'い': Unicode U+3044 (category Lo: Letter, other)

In [121]:
str[13]

'😄': Unicode U+1F604 (category So: Symbol, other)

In [122]:
str[17]

'漢': Unicode U+6F22 (category Lo: Letter, other)

In [123]:
str[12]

LoadError: StringIndexError: invalid index [12], valid nearby indices [10]=>'う', [13]=>'😄'

### 2-7-5. 型アノテーション

#### コード2-95. 複合型の例(1)：簡単な定義例（再掲）

```julia
julia> struct Point
           x
           y
       end

julia> pt = Point(1.0, 2.0)
Point(1.0, 2.0)

julia> pt.x
1.0

julia> pt.y
2.0
```

#### コード2-114. 型アノテーション(1)：複合型のフィールドへの型アノテーション

In [124]:
struct IntPoint
    x::Int
    y::Int
end

In [125]:
IntPoint(1, 3)

IntPoint(1, 3)

In [126]:
IntPoint(2.0, 3.2)

LoadError: InexactError: Int64(3.2)

#### コード2-115. 型アノテーション(2)：ローカル変数への型アノテーション（＝変数の型の指定）

In [127]:
function typeannotatesample()
    n::Int = 0
    n = 3.0
    n
end

typeannotatesample (generic function with 1 method)

In [128]:
result = typeannotatesample()

3

In [129]:
typeof(result)

Int64

#### コード2-116. 型アノテーション(3)：式への型アノテーション（＝型検査）

In [130]:
function typeassertsample(fn::Function)
    n = fn()::Int
    n
end

typeassertsample (generic function with 1 method)

In [131]:
typeassertsample() do
    1 + 2
end

3

In [132]:
typeassertsample() do
    sin(π)
end

LoadError: TypeError: in typeassert, expected Int64, got a value of type Float64