In [1]:
versioninfo()

Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores


## 3-2. 標準ライブラリ

### 3-2-1. Printf

#### コード3-48. `Printf`(1)：`@printf` マクロ

In [2]:
using Printf

In [3]:
x = 24.927;

In [4]:
@printf("%d", x)  # 整数に丸めて表示

25

In [5]:
@printf("%.2f", x)  # 小数点以下2桁に丸めて表示

24.93

In [6]:
@printf("%.5f", x)  # 小数点以下5桁まで表示（0埋め）

24.92700

In [7]:
@printf("%.10g", x)  # 小数点以外で合計10桁まで表示、ただし後ろに続く0は出力しない

24.927

In [8]:
@printf(stderr, "%d", x)  # 整数に丸めて標準エラー出力に出力

25

In [9]:
# open("sampleout.txt", "w") do f
#     @printf(f, "%d", x)
# end  
# ↑ファイルに出力（動作例割愛）

#### コード3-49. `Printf`(2)：`@sprintf` マクロ

In [10]:
using Printf

In [11]:
x = 24.927;

In [12]:
@sprintf("%d", x)  # 整数に丸めて文字列化

"25"

In [13]:
@sprintf("%.2f", x)  # 小数点以下2桁に丸めて文字列化

"24.93"

In [14]:
@sprintf("%.5f", x)  # 小数点以下5桁まで文字列化（0埋め）

"24.92700"

In [15]:
@sprintf("%.10g", x)  # 小数点以外で合計10桁まで文字列化、ただし後ろに続く0は出力しない

"24.927"

#### コード3-50. `Printf`(3)：`Printf.format()` 関数(1)、`Printf.format"～"` 書式文字列リテラル

In [16]:
using Printf

In [17]:
x = 24.927;

In [18]:
Printf.format(Printf.format"%d", x)  # 整数に丸めて文字列化

"25"

In [19]:
Printf.format(Printf.format"%.2f", x)  # 小数点以下2桁に丸めて文字列化

"24.93"

In [20]:
Printf.format(Printf.format"%.5f", x)  # 小数点以下5桁まで文字列化（0埋め）

"24.92700"

In [21]:
Printf.format(Printf.format"%.10g", x)  # 小数点以外で合計10桁まで文字列化

"24.927"

#### コード3-51. `Printf`(4)：`Printf.format()` 関数(1)、`Printf.Format` オブジェクト

In [22]:
using Printf

In [23]:
x = 24.927;

In [24]:
function createformat(v)
    Printf.Format("%.$(ceil(Int, log10(v)) + 5)g")
end

createformat (generic function with 1 method)

In [25]:
Printf.format(createformat(x), x)

"24.927"

In [26]:
Printf.format(createformat(π), π)

"3.14159"

In [27]:
Printf.format(createformat(10000000), 10000000)

"10000000"

#### コード3-53. `Printf`(5)：`Printf.format()` 関数(3)

In [28]:
using Printf

In [29]:
x = 24.927;

In [30]:
Printf.format(stdout, Printf.format"%d", x)  # 整数に丸めて表示

25

In [31]:
Printf.format(stdout, Printf.format"%.2f", x)  # 小数点以下2桁に丸めて表示

24.93

In [32]:
Printf.format(stdout, Printf.format"%.5f", x)  # 小数点以下5桁まで表示（0埋め）

24.92700

In [33]:
Printf.format(stdout, Printf.format"%.10g", x)  # 小数点以外で合計10桁まで表示、ただし後ろに続く0は出力しない

24.927

### 3-2-2. Dates

#### コード3-53. `Dates` パッケージの使用例 (1)：範囲オブジェクトの生成

In [34]:
using Dates

In [35]:
Date(2021,1,1):Date(2021,12,31)

LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type Day
Closest candidates are:
  convert(::Type{T}, ::Dates.CompoundPeriod) where T<:Period at ~/julia-1.8.5/share/julia/stdlib/v1.8/Dates/src/periods.jl:363
  convert(::Type{Day}, ::Week) at ~/julia-1.8.5/share/julia/stdlib/v1.8/Dates/src/periods.jl:433
  convert(::Type{Day}, ::Hour) at ~/julia-1.8.5/share/julia/stdlib/v1.8/Dates/src/periods.jl:441
  ...

In [36]:
Date(2021,1,1):Day(1):Date(2021,12,31)

Date("2021-01-01"):Day(1):Date("2021-12-31")

In [37]:
length(Date(2021,1,1):Day(1):Date(2021,12,31))

365

In [38]:
collect(Date(2021,1,31):Month(1):Date(2021,12,31))

12-element Vector{Date}:
 2021-01-31
 2021-02-28
 2021-03-31
 2021-04-30
 2021-05-31
 2021-06-30
 2021-07-31
 2021-08-31
 2021-09-30
 2021-10-31
 2021-11-30
 2021-12-31

In [39]:
collect(Date(2000,2,29):Year(1):Date(2100,2,28))

101-element Vector{Date}:
 2000-02-29
 2001-02-28
 2002-02-28
 2003-02-28
 2004-02-29
 2005-02-28
 2006-02-28
 2007-02-28
 2008-02-29
 2009-02-28
 2010-02-28
 2011-02-28
 2012-02-29
 ⋮
 2089-02-28
 2090-02-28
 2091-02-28
 2092-02-29
 2093-02-28
 2094-02-28
 2095-02-28
 2096-02-29
 2097-02-28
 2098-02-28
 2099-02-28
 2100-02-28

#### コード3-54. `Dates` パッケージの使用例 (2)：日時書式文字列リテラル

In [40]:
using Dates

In [41]:
dt1 = today()

2023-01-27

In [42]:
dtm1 = now()

2023-01-27T13:55:25.444

In [43]:
Dates.format(dt1, dateformat"yyyy/mm/dd")

"2023/01/27"

In [44]:
Dates.format(dtm1, dateformat"yyyy年m月d日 H時M分S秒")

"2023年1月27日 13時55分25秒"

In [45]:
Date("2010/1/2", dateformat"y/m/d")  # `parse(Date, "2010/1/2", dateformat"y/m/d")` でもOK

2010-01-02

#### コード3-55. `Dates` パッケージの使用例 (3)

In [46]:
using Dates

In [47]:
dt1 = today()

2023-01-27

In [48]:
dtm1 = now()

2023-01-27T13:55:25.991

In [49]:
Date(dtm1) == dt1

true

In [50]:
dt1 + Day(1)  # 明日

2023-01-28

In [51]:
dt1 - Day(1)  # 昨日、`dt1 + Day(-1)` でも同じ

2023-01-26

In [52]:
dtm1 + Hour(2)  # 2時間後

2023-01-27T15:55:25.991

In [53]:
dtm1 - Hour(2)  # 2時間前

2023-01-27T11:55:25.991

In [54]:
dt1 - Date(1976, 1, 1) + Day(1)  # 1976年1月1日 からの日数

17194 days

In [55]:
dayofyear(dt1)  # == Dates.value(dt1 - Date(2021) + Day(1))

27

In [56]:
dtm1 - DateTime(2021, 1, 1)  # 2021年1月1日 0時0分0秒 からのミリ秒数

65368525991 milliseconds

In [57]:
floor(dtm1 - DateTime(2021, 1, 1), Second)  # ミリ秒を秒に変換

65368525 seconds

In [58]:
dayname(dt1)

"Friday"

### 3-2-3. Statistics

#### コード3-56. `Statistics` パッケージ使用例 (1): `mean()`、`median()`、`middle()`、`quantile()`

In [59]:
using Statistics

In [60]:
x = [2.0, 1.0, 3.0, 5.0, 10.2, 16.8]

6-element Vector{Float64}:
  2.0
  1.0
  3.0
  5.0
 10.2
 16.8

In [61]:
mean(x)  # 平均値

6.333333333333333

In [62]:
median(x)  # 中央値

4.0

In [63]:
middle(x)  # 中点値

8.9

In [64]:
quantile(x, 0.25:0.25:0.75)  # 四分位数

3-element Vector{Float64}:
 2.25
 4.0
 8.899999999999999

#### コード3-57. `Statistics` パッケージ使用例 (2): `std()`、`var()`

In [65]:
using Statistics

In [66]:
x = [2.0, 1.0, 3.0, 5.0, 10.2, 16.8];

In [67]:
std(x)  # 不偏標準偏差（補正標本標準偏差）

6.076402444429324

In [68]:
std(x, corrected=false)  # 標本標準偏差（非補正標本標準偏差）または母標準偏差

5.546971145489121

In [69]:
var(x)  # 不偏分散（補正標本分散）

36.92266666666667

In [70]:
var(x, corrected=false)  # 標本分散（非補正標本分散）または母分散

30.768888888888892

#### コード3-58. `Statistics` パッケージ使用例 (3): 多次元配列への適用（`dims=～` キーワード引数指定）

In [71]:
using Statistics

In [72]:
M = [2.0 3.0 5.0; 1.0 10.2 16.8]

2×3 Matrix{Float64}:
 2.0   3.0   5.0
 1.0  10.2  16.8

In [73]:
mean(M, dims=1)

1×3 Matrix{Float64}:
 1.5  6.6  10.9

In [74]:
mean(M, dims=2)

2×1 Matrix{Float64}:
 3.3333333333333335
 9.333333333333334

In [75]:
median(M, dims=2)

2×1 Matrix{Float64}:
  3.0
 10.2

In [76]:
std(M, dims=2)

2×1 Matrix{Float64}:
 1.5275252316519465
 7.935573913292809

In [77]:
std(M, corrected=false, dims=2)

2×1 Matrix{Float64}:
 1.247219128924647
 6.4793689679028335

In [78]:
var(M, dims=2)

2×1 Matrix{Float64}:
  2.333333333333333
 62.97333333333334

In [79]:
var(M, corrected=false, dims=2)

2×1 Matrix{Float64}:
  1.5555555555555554
 41.98222222222223

#### コード3-59. `Statistics` パッケージ使用例 (4): 多次元配列への適用（`mapslices()` 関数利用）

In [80]:
using Statistics

In [81]:
M = [2.0 3.0 5.0; 1.0 10.2 16.8];

In [82]:
middle(M)

8.9

In [83]:
mapslices(middle, M, dims=1)  # 列ごとの中点値

1×3 Matrix{Float64}:
 1.5  6.6  10.9

In [84]:
mapslices(middle, M, dims=2)  # 行ごとの中点値

2×1 Matrix{Float64}:
 3.5
 8.9

In [85]:
quartile(x) = quantile(x, 0.25:0.25:0.75)  # 簡単のため四分位数を算出する関数を定義

quartile (generic function with 1 method)

In [86]:
mapslices(quartile, M, dims=1)  # 結果の各列が元の行列の各列の四分位数

3×3 Matrix{Float64}:
 1.25  4.8   7.95
 1.5   6.6  10.9
 1.75  8.4  13.85

In [87]:
mapslices(quartile, M, dims=2)  # 結果の各行が元の行列の各行の四分位数

2×3 Matrix{Float64}:
 2.5   3.0   4.0
 5.6  10.2  13.5

### 3-2-4. LinearAlgebra

#### コード3-60. `LinearAlgebra` パッケージ使用例 (1): `⋅` 演算子（`dot()` 関数）、`×` 演算子（`cross()` 関数）

In [88]:
using LinearAlgebra

In [89]:
x = [2.0, 1.0, 3.0];

In [90]:
y = [2., 3., 1.];

In [91]:
x ⋅ y  # `dot(x, y)`, `x'y` でも同じ

10.0

In [92]:
x × y  # `cross(x, y)` でも同じ

3-element Vector{Float64}:
 -8.0
  4.0
  4.0

In [93]:
A = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.];

In [94]:
dot(x, A, y)  # `x' * A * y` としても計算結果は同じ

-41.0

#### コード3-61. `LinearAlgebra` パッケージ使用例 (2): `norm()`、`opnorm()`

In [95]:
using LinearAlgebra

In [96]:
x = [2.0, 1.0, 3.0];

In [97]:
norm(x)  # == `√(x'x)`

3.7416573867739413

In [98]:
norm(x, 1)  # == `sum(abs, x)`

6.0

In [99]:
norm(x, Inf)  # == `max(abs, x)`

3.0

In [100]:
A = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.];

In [101]:
norm(A)  # フロベニウスノルム、== `sqrt(sum(x->abs(x)^2, A))`

124.44677577181339

In [102]:
opnorm(A)  # 作用素ノルム

123.47723179013158

#### コード3-62. `LinearAlgebra` パッケージ使用例 (3): `rank()`、`tr()`、`det()`、`pinv()`

In [103]:
using LinearAlgebra

In [104]:
A = [1. 2. 3.; 4. 5. 6.; 7. 8. 9.]

3×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

In [105]:
rank(A)  # `rank(A) < minimum(size(A))` となる行列をランク落ちと言う
         # （特に正方行列なら正則行列ではない）

2

In [106]:
tr(A)

15.0

In [107]:
det(A)

0.0

In [108]:
pinv(A)  # 正則行列でない行列でも `pinv(A)` は計算できる

3×3 Matrix{Float64}:
 -0.638889   -0.166667      0.305556
 -0.0555556   4.16334e-17   0.0555556
  0.527778    0.166667     -0.194444

In [109]:
x = [1.0, 2.0, 4.0];

In [110]:
# `A \ x` は `SingularException(3)` 発生
pinv(A) * x  # `A * ○ == [1, 2, 4]` となる `○` の誤差(最)小解

3-element Vector{Float64}:
 0.2500000000000002
 0.1666666666666668
 0.08333333333333348

In [111]:
pinv(x) * x ≈ 1.0

true

#### コード3-63. `LinearAlgebra` パッケージ使用例 (4): 各種行列（抜粋）

In [112]:
A = [1. 2. 3.; 4. 5. 6.; 7. 8. 9.];

In [113]:
Symmetric(A)  # 対称行列

3×3 Symmetric{Float64, Matrix{Float64}}:
 1.0  2.0  3.0
 2.0  5.0  6.0
 3.0  6.0  9.0

In [114]:
Hermitian(A+fill(im,3,3))  # エルミート行列

3×3 Hermitian{ComplexF64, Matrix{ComplexF64}}:
 1.0+0.0im  2.0+1.0im  3.0+1.0im
 2.0-1.0im  5.0+0.0im  6.0+1.0im
 3.0-1.0im  6.0-1.0im  9.0+0.0im

In [115]:
Diagonal(A)  # 対角行列

3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   5.0   ⋅ 
  ⋅    ⋅   9.0

In [116]:
UpperTriangular(A)  # 上三角行列

3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  2.0  3.0
  ⋅   5.0  6.0
  ⋅    ⋅   9.0

In [117]:
LowerTriangular(A)  # 下三角行列

3×3 LowerTriangular{Float64, Matrix{Float64}}:
 1.0   ⋅    ⋅ 
 4.0  5.0   ⋅ 
 7.0  8.0  9.0

#### コード3-64. `LinearAlgebra` パッケージ使用例 (5): 行列の分解

In [118]:
A = [3. 5. 2.; 5. 7. 3.; 2. 3. 1.]

3×3 Matrix{Float64}:
 3.0  5.0  2.0
 5.0  7.0  3.0
 2.0  3.0  1.0

In [119]:
factorize(A)  # == bunchkaufman(A)

BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
D factor:
3×3 Tridiagonal{Float64, Vector{Float64}}:
 -0.5   0.0        ⋅ 
  0.0  -0.285714  0.0
   ⋅    0.0       7.0
U factor:
3×3 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.5  0.714286
  ⋅   1.0  0.428571
  ⋅    ⋅   1.0
permutation:
3-element Vector{Int64}:
 1
 3
 2

In [120]:
cholesky(A+I)

Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 2.0  2.5      1.0
  ⋅   1.32288  0.377964
  ⋅    ⋅       0.92582

In [121]:
isposdef(A)

false

In [122]:
lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0  0.0   0.0
 0.6  1.0   0.0
 0.4  0.25  1.0
U factor:
3×3 Matrix{Float64}:
 5.0  7.0   3.0
 0.0  0.8   0.2
 0.0  0.0  -0.25

In [123]:
qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.486664   0.841191   -0.235702
 -0.811107  -0.535303   -0.235702
 -0.324443   0.0764719   0.942809
R factor:
3×3 Matrix{Float64}:
 -6.16441  -9.0844    -3.73109
  0.0       0.688247   0.152944
  0.0       0.0       -0.235702

In [124]:
y1 = A * [1., 2., 3.]

3-element Vector{Float64}:
 19.0
 28.0
 11.0

In [125]:
y2 = (A + I) * [1., 2., 3.]

3-element Vector{Float64}:
 20.0
 30.0
 14.0

In [126]:
factorize(A) \ y1 ≈ [1, 2, 3]

true

In [127]:
bunchkaufman(A) \ y1 ≈ [1, 2, 3]

true

In [128]:
cholesky(A+I) \ y2 ≈ [1, 2, 3]

true

In [129]:
lu(A) \ y1 ≈ [1, 2, 3]

true

In [130]:
qr(A) \ y1 ≈ [1, 2, 3]

true