In [1]:
versioninfo()

Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores


## 3-1. 便利な標準関数たち

### 3-1-1. 演算系(1) 除算・剰余算系

#### 整数除算関数

In [2]:
div(5, 2)

2

In [3]:
div(-5, 2)

-2

In [4]:
fld(5, 2)

2

In [5]:
fld(-5, 2)

-3

In [6]:
cld(5, 2)

3

In [7]:
cld(-5, 2)

-2

##### コード3-1. `÷`演算子の関数としての利用例

In [8]:
÷(-5, 2)

-2

In [9]:
÷(-5, 2, RoundDown)

-3

In [10]:
÷(-5, 2, RoundNearest)

-2

In [11]:
÷(-5, 2, RoundNearestTiesAway)

-3

#### 整数剰余算関数

#### 整数除算・剰余算複合関数

#### 値域を指定した整数剰余算関数と整数除算関数

#### コラム. `mod1()` 関数の使い途

##### 仮想コード3-a. `mod1()` 関数の使用例（`Dates` モジュール内の実装イメージ）

```julia
# Monday = 1....Sunday = 7
dayofweek(date) = mod1(days(date), 7)

days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday",
                "Friday", "Saturday", "Sunday"]

dayname(date) = days_of_week[dayofweek(date)]
```

#### その他の除算・剰余算関連関数

##### コード3-2. `\`演算子の例

In [12]:
2 \ 3  # == `3 / 2`

1.5

In [13]:
1//2 \ 3//4  # == `2 * 3//4`

3//2

In [14]:
A = Float64[1 2; 3 4]; x = [1, 1];
A \ x  # == `A^(-1) * x`

2-element Vector{Float64}:
 -1.0
  1.0

### 3-1-2. 演算系(2) 結合演算

#### 積和演算

##### コード3-3. `fma()` 関数、`muladd()` 関数の例

In [15]:
fma(0.1, 0.2, 0.3)

0.32

In [16]:
muladd(0.1, 0.2, 0.3)

0.32

In [17]:
A = [1 2; 3 4]; x = [-1, 1]; y = 100;
muladd(A, x, y)

2-element Vector{Int64}:
 101
 101

In [18]:
fma(A, x, y)

LoadError: MethodError: no method matching fma(::Matrix{Int64}, ::Vector{Int64}, ::Int64)
Closest candidates are:
  fma(::Integer, ::Integer, ::Integer) at promotion.jl:470
  fma(::T, ::T, ::T) where T<:Number at promotion.jl:469
  fma(::Number, ::Number, ::Number) at promotion.jl:424

#### 冪剰余演算

##### コード3-4. `powermod()` 関数の例

In [19]:
powermod(5, 2, 20)  # == mod(5^2, 20)

5

In [20]:
powermod(1518500249, 3, 100)

49

In [21]:
mod(1518500249^3, 100)  # オーバーフローが発生するため結果が期待通りにならない例

53

### 3-1-3. 演算系(3) その他の演算系関数

### 3-1-4. 数学系(1) 三角関数、指数関数、対数関数

In [22]:
sin(2π)

-2.4492935982947064e-16

In [23]:
sind(360)

0.0

In [24]:
sinpi(2)

0.0

In [25]:
sind(360) == sinpi(2) == 0.0

true

### 3-1-5. 数学系(2) その他の数学関数

### 3-1-6. 文字列関連関数

#### 文字・文字列情報取得関数・演算子

##### コード3-5. `nextind()` 関数、`eachindex()` 関数の使用例

In [26]:
str = "abcあいう😄漢字";

In [27]:
[nextind(str, 0, v) for v=1:length(str)]

9-element Vector{Int64}:
  1
  2
  3
  4
  7
 10
 13
 17
 20

In [28]:
# 参考：上記と同じ結果になるコード
collect(eachindex(str))  # `collect(keys(str))` でもOK

9-element Vector{Int64}:
  1
  2
  3
  4
  7
 10
 13
 17
 20

#### 文字・文字列比較関数・演算子

#### 文字列操作関数・演算子

##### コード3-6. `chop()` 関数の例

In [29]:
str = "abcあいう😄漢字";

In [30]:
chop(str)

"abcあいう😄漢"

In [31]:
chop(str, head=1)

"bcあいう😄漢"

In [32]:
chop(str, tail=3)

"abcあいう"

In [33]:
chop(str, head=3, tail=0)

"あいう😄漢字"

##### コード3-7. `split()` 関数、`rsplit()` 関数の例

In [34]:
split("A B  C") == ["A", "B", "C"]

true

In [35]:
split("A B  C", keepempty=true) == ["A", "B", "", "C"]

true

In [36]:
split("A B C", limit=2) == ["A", "B C"]

true

In [37]:
rsplit("A B C", limit=2) == ["A B", "C"]

true

In [38]:
split("A2B34C", 'B') == ["A2", "34C"]

true

In [39]:
rsplit("A2B34C", '0':'9') == ["A", "B", "", "C"]

true

In [40]:
rsplit("A2B34C", '0':'9', keepempty=false) == ["A", "B", "C"]

true

##### コード3-8. `strip()` 関数、`lstrip()` 関数、`rstrip()` 関数の例

In [41]:
strip("   ABC  ") == "ABC"

true

In [42]:
lstrip("   ABC  ") == "ABC  "

true

In [43]:
rstrip("   ABC  ") == "   ABC"

true

In [44]:
strip("{3, 5}\n", ['{', '}', '\n'])

"3, 5"

In [45]:
strip("{3, 5}\n") do c
    isspace(c) || ispunct(c)
end

"3, 5"

#### 文字列検索・置換関数

##### コード3-9. `findxxxx()` 系の関数の例(1)

In [46]:
str = "rem2pi(42.195)";

In [47]:
findfirst(isdigit, str)

4

In [48]:
str[findfirst(isdigit, str)]

'2': ASCII/Unicode U+0032 (category Nd: Number, decimal digit)

In [49]:
findnext(isdigit, str, 5)

8

In [50]:
str[findnext(isdigit, str, 5)]

'4': ASCII/Unicode U+0034 (category Nd: Number, decimal digit)

In [51]:
findlast(isdigit, str)

13

In [52]:
str[findlast(isdigit, str)]

'5': ASCII/Unicode U+0035 (category Nd: Number, decimal digit)

In [53]:
findprev(isdigit, str, 12)

12

In [54]:
str[findprev(isdigit, str, 12)]

'9': ASCII/Unicode U+0039 (category Nd: Number, decimal digit)

In [55]:
findfirst("pi", str)

5:6

In [56]:
str[findfirst("pi", str)]

"pi"

##### コード3-10. `occursin()` 関数、`contains()` 関数の例

In [57]:
occursin("pi", "rem2pi(42.195)")

true

In [58]:
contains("rem2pi(42.195)", "pi")

true

In [59]:
pred1 = occursin("rem2pi(42.195)");

In [60]:
map(pred1, ['.', "NOT_EXISTS", r"\d+"]) == [true, false, true]

true

In [61]:
pred2 = contains(r"\d{2,}");  # 数字2文字以上、という正規表現

In [62]:
filter(pred2, ["42.195", "Julia v1.6", "ALLALPHABETS"])

1-element Vector{String}:
 "42.195"

##### コード3-11. `replace()` 関数の例(1)

In [63]:
replace("123ABCあいう漢字", 'A'=>'α')

"123αBCあいう漢字"

In [64]:
replace("123ABCあいう漢字", "ABC"=>"XYZ", 'あ':'ん'=>"")  # Julia v1.7 以降で有効

"123XYZ漢字"

In [65]:
replace(replace("123ABCあいう漢字", "ABC"=>"XYZ"), 'あ':'ん'=>"")  # Julia v1.6 ならこちら

"123XYZ漢字"

In [66]:
replace("123ABCあいう漢字", isuppercase=>lowercase)

"123abcあいう漢字"

#### Julia の正規表現

##### コード3-12. 正規表現の使用例（`occursin()`/`contains()`）

In [67]:
occursin(r"^#[0-9a-f]{6}$"i, "#FFA800")

true

In [68]:
contains("ThereIsNoSpace!", r"\s+")

false

In [69]:
pred2 = contains(r"\d{2,}");  # 数字2文字以上、という正規表現

In [70]:
filter(pred2, ["42.195", "Julia v1.6", "ALLALPHABETS"])

1-element Vector{String}:
 "42.195"

##### コード3-13. `match()` 関数の例

In [71]:
m = match(r"\d+", "123ABCあいう漢字")

RegexMatch("123")

In [72]:
m.match  # マッチした部分文字列

"123"

In [73]:
m = match(r"(\d+)(?<ABC>[ABC]+)", "123ABCあいう漢字")

RegexMatch("123ABC", 1="123", ABC="ABC")

In [74]:
m.match  # マッチした部分文字列

"123ABC"

In [75]:
m[1]  # キャプチャグループ（1番目）

"123"

In [76]:
m[2]  # キャプチャグループ（2番目）

"ABC"

In [77]:
m["ABC"]  # 名前付きキャプチャグループ（"ABC"）

"ABC"

In [78]:
match(r"\s", "ThereIsNoSpace!") === nothing

true

##### コード3-14. `eachmatch()` 関数の例

In [79]:
for m in eachmatch(r"\w+", "Yes, I have a number.")
    println(m.match)
end

Yes
I
have
a
number


In [80]:
[m[1] for m in eachmatch(r"_(\d+)_", "1_23_456_78_9", overlap=true)]

3-element Vector{SubString{String}}:
 "23"
 "456"
 "78"

##### コード3-15. `replace()` 関数の例(2)：正規表現、置換文字列リテラルの例

In [81]:
replace("123ABCあいう漢字", r"\d"=>s"\0\0")

"112233ABCあいう漢字"

In [82]:
replace("123ABCあいう漢字", r"\d"=>s"\g<0>1")  # `s"\01"` だと "PCRE error: unknown substring" となる

"112131ABCあいう漢字"

In [83]:
replace("123ABCあいう漢字", r"(\d+)(?<abc>[a-z]+)"ia=>s"\g<abc>\1")  # `s"\2\1"` でも同じ

"ABC123あいう漢字"

#### パターンに指定出来るもの

##### コード3-16. `findxxxx()` 系の関数の例(2)：対応していないパターンの述語関数による代替

In [84]:
findfirst('A':'Z', "123ABCあいう漢字")  # MethodError 発生

LoadError: MethodError: no method matching findfirst(::StepRange{Char, Int64}, ::String)
Closest candidates are:
  findfirst(::AbstractArray) at array.jl:1992
  findfirst(::AbstractChar, ::AbstractString) at strings/search.jl:130
  findfirst(::AbstractString, ::AbstractString) at strings/search.jl:110
  ...

In [85]:
findfirst(∈('A':'Z'), "123ABCあいう漢字")

4

In [86]:
findall('A', "ABCABCABCA")  # Julia v1.7 ならOK、v1.6だと MethodError 発生

4-element Vector{Int64}:
  1
  4
  7
 10

In [87]:
findall(==('A'), "ABCABCABCA") == [1, 4, 7, 10]  # Julia v1.6 でも v1.7 でもOK

true

### 3-1-7. 配列・集合演算

#### コレクション情報取得関数・演算子

##### コード3-17. コレクション情報取得関数の例

In [88]:
A = [100z + 10y + x for x=1:3, y=1:4, z=1:2];

In [89]:
ndims(A)

3

In [90]:
size(A)

(3, 4, 2)

In [91]:
size(A, 1)  # == size(A)[1]

3

In [92]:
axes(A)

(Base.OneTo(3), Base.OneTo(4), Base.OneTo(2))

In [93]:
axes(A, 2)  # == axes(A)[2]

Base.OneTo(4)

In [94]:
for x in axes(A, 1), y in axes(A, 2), z in axes(A, 3)
    println(A[x, y, z])
end

111
211
121
221
131
231
141
241
112
212
122
222
132
232
142
242
113
213
123
223
133
233
143
243


In [95]:
axes((:a, :b, :c))

(Base.OneTo(3),)

#### 配列関連関数・演算子(1) 配列生成関連

##### コード3-18. 配列生成の例(1)：コンストラクタ利用

In [96]:
Vector{Int}(undef, 5)  # 結果は実行する度に変化する

5-element Vector{Int64}:
 25769803780
 34359738376
  4294967304
           0
           0

In [97]:
Matrix{Float64}(undef, 2, 2)  # 結果は実行する度に変化する

2×2 Matrix{Float64}:
 6.89892e-310  6.89892e-310
 6.89892e-310  6.89892e-310

In [98]:
Array{UInt8}(undef, 2, 3, 2)  # 結果は実行する度に変化する

2×3×2 Array{UInt8, 3}:
[:, :, 1] =
 0x90  0x68  0xff
 0x93  0x70  0x7e

[:, :, 2] =
 0x00  0xd0  0x17
 0x00  0x97  0x7d

##### コード3-19. 配列生成の例(2)：`zeros()`、`ones()`、`fill()`

In [99]:
zeros(Int, 5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

In [100]:
ones(2, 2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [101]:
fill(0x7f, 2, 2)

2×2 Matrix{UInt8}:
 0x7f  0x7f
 0x7f  0x7f

##### コード3-20. 配列生成の例(3)：`BitArray`（`BitVector`、`BitMatrix`）の生成

In [102]:
BitArray(undef, 2, 3)  # 結果は実行する度に変化する

2×3 BitMatrix:
 0  0  0
 0  0  0

In [103]:
trues(3, 4, 2)

3×4×2 BitArray{3}:
[:, :, 1] =
 1  1  1  1
 1  1  1  1
 1  1  1  1

[:, :, 2] =
 1  1  1  1
 1  1  1  1
 1  1  1  1

In [104]:
typeof(1:2:10 .== [1, 3, 5, 7, 9])

BitVector (alias for BitArray{1})

##### コード3-21. 配列生成の例(4)：`similar()`

In [105]:
A = UInt8[1 2; 3 4];

In [106]:
similar(A)  # `Array{UInt8}(undef, 2, 2)` と同じ

2×2 Matrix{UInt8}:
 0x50  0xa7
 0x6c  0xf8

In [107]:
similar(A, 3, 4, 2)  # `Array{UInt8}(undef, 3, 4, 2)` と同じ

3×4×2 Array{UInt8, 3}:
[:, :, 1] =
 0xc6  0x00  0x00  0x02
 0x7e  0x00  0x00  0x02
 0x00  0x00  0x02  0x02

[:, :, 2] =
 0x01  0x02  0x00  0x7e
 0x00  0x02  0x00  0x00
 0x02  0x02  0xfe  0x00

In [108]:
similar(A, Float64)  # `Array{Float64}(undef, 2, 2)` と同じ

2×2 Matrix{Float64}:
 6.89892e-310  6.89892e-310
 6.89892e-310  6.89892e-310

In [109]:
B = BitArray(undef, 2, 2);

In [110]:
similar(B, 10)  # `BitArray(undef, 10)` と同じ

10-element BitVector:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

#### 配列関連関数・演算子(2) 配列加工・更新

#### 配列関連関数・演算子(3) ベクトル・行列関連

##### コード3-22. 行列・ベクトル演算の例

In [111]:
A = [1 2; 3 4];

In [112]:
x = [-1, 1];

In [113]:
y = A * x

2-element Vector{Int64}:
 1
 1

In [114]:
A \ y  # `== x`、ただし要素の型は `Float64`

2-element Vector{Float64}:
 -1.0
  1.0

##### コード3-23. `transpose()`、`adjoint()`（`○'`）の例

In [115]:
A = [1 2; 3 4]; x = [-1, 1];

In [116]:
transpose(A)

2×2 transpose(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [117]:
A'  # `adjoint(A)` としても同じ

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [118]:
A'A  # A' * A と同じ

2×2 Matrix{Int64}:
 10  14
 14  20

In [119]:
C = [1+1im -1+1im; 1-1im -1-1im];

In [120]:
transpose(C)

2×2 transpose(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
  1+1im   1-1im
 -1+1im  -1-1im

In [121]:
C'  # `adjoint(C)` としても同じ

2×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
  1-1im   1+1im
 -1-1im  -1+1im

In [122]:
transpose(x)

1×2 transpose(::Vector{Int64}) with eltype Int64:
 -1  1

In [123]:
x'  # `adjoint(x)` としても同じ

1×2 adjoint(::Vector{Int64}) with eltype Int64:
 -1  1

In [124]:
x'A  # x' * A と同じ

1×2 adjoint(::Vector{Int64}) with eltype Int64:
 2  2

In [125]:
x'x  # x' * x と同じ

2

#### 配列関連関数・演算子(4) デック（両端キュー）

##### コード3-24. デック(1)：先頭/末尾への追加/取り出しの例

In [126]:
q = [1, 2, 3, 4, 5];

In [127]:
push!(q, 11, 12, 13)

8-element Vector{Int64}:
  1
  2
  3
  4
  5
 11
 12
 13

In [128]:
pop!(q)

13

In [129]:
pop!(q)

12

In [130]:
pop!(q)

11

In [131]:
q

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [132]:
pushfirst!(q, -2, -1)

7-element Vector{Int64}:
 -2
 -1
  1
  2
  3
  4
  5

In [133]:
popfirst!(q)

-2

In [134]:
popfirst!(q)

-1

In [135]:
prepend!(append!(q, 6:9), -2:0)

12-element Vector{Int64}:
 -2
 -1
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9

##### コード3-25. デック(2)：任意の位置への追加/取り出し/削除の例

In [136]:
q = [10, 20, 30, 40, 50];

In [137]:
insert!(q, 4, 35)

6-element Vector{Int64}:
 10
 20
 30
 35
 40
 50

In [138]:
popat!(q, 4)

35

In [139]:
deleteat!(q, 3:4)

3-element Vector{Int64}:
 10
 20
 50

In [140]:
popat!(q, 4)  # エラー

LoadError: BoundsError: attempt to access 3-element Vector{Int64} at index [4]

In [141]:
popat!(q, 4, 999)

999

#### 配列関連関数・演算子(5) 集計・畳み込み関連関数

##### コード3-26. 集計・畳み込み関連関数(1)：`sum()`、`prod()`、`maximum()`、`minimum()` の例

In [142]:
A = [1 2; 3 4];

In [143]:
sum(A)

10

In [144]:
sum(A, dims=1)

1×2 Matrix{Int64}:
 4  6

In [145]:
sum(A, dims=2)

2×1 Matrix{Int64}:
 3
 7

In [146]:
prod(A)

24

In [147]:
prod(A, dims=1)

1×2 Matrix{Int64}:
 3  8

In [148]:
prod(A, dims=2)

2×1 Matrix{Int64}:
  2
 12

In [149]:
maximum(A)

4

In [150]:
maximum(A, dims=1)

1×2 Matrix{Int64}:
 3  4

In [151]:
maximum(A, dims=2)

2×1 Matrix{Int64}:
 2
 4

In [152]:
minimum(A)

1

In [153]:
minimum(A, dims=1)

1×2 Matrix{Int64}:
 1  2

In [154]:
minimum(A, dims=2)

2×1 Matrix{Int64}:
 1
 3

In [155]:
M = [100z + 10y + x for x=1:2, y=1:2, z=1:2];

In [156]:
sum(M, dims=(1, 3))

1×2×1 Array{Int64, 3}:
[:, :, 1] =
 646  686

##### コード3-27. 集計・畳み込み関連関数の例(2)

In [157]:
A = [1 2; 3 4];

In [158]:
reduce(+, A, dims=1)  # `== sum(A, dims=1)`

1×2 Matrix{Int64}:
 4  6

In [159]:
reduce(-, A, dims=2, init=0)  # `reduce(-, A, dims=2)` だとエラーになる

2×1 Matrix{Int64}:
 -3
 -7

In [160]:
x = [1, 2, 3, 4];

In [161]:
reduce(-, x)  # エラーにはならないが結果が保証されているわけでもない

-8

In [162]:
foldl(-, x)  # `== (((1 - 2) - 3) - 4)`

-8

In [163]:
foldr(-, x)  # `== (1 - (2 - (3 - 4)))`

-2

In [164]:
foldr((n, x) -> n + inv(x), [1;fill(2,100)])  # √2 の近似値

1.4142135623730951

##### コード3-28. 集計・畳み込み関連関数(3)：`mapslices()` の例

In [165]:
A = [1 2; 3 4];

In [166]:
norm2(v) = √(v'v)

norm2 (generic function with 1 method)

In [167]:
mapslices(norm2, A, dims=1)

1×2 Matrix{Float64}:
 3.16228  4.47214

In [168]:
mapslices(norm2, A, dims=2)

2×1 Matrix{Float64}:
 2.23606797749979
 5.0

In [169]:
mapslices(norm2, [1 2 3; 4 5 6; 7 8 9], dims=1)

1×3 Matrix{Float64}:
 8.12404  9.64365  11.225

#### 配列関連関数・演算子(6) 検索・置換関連関数

##### コード3-29. `findxxxx()` 系の関数の例(3)：配列への適用

In [170]:
x = rand(10)  # 実行する度に結果は変わる

10-element Vector{Float64}:
 0.46977390476737824
 0.5823284907214202
 0.1680122529642395
 0.8763819348041276
 0.20764740625792855
 0.8865713995475546
 0.6212554970628538
 0.36252932924184234
 0.5982545958109509
 0.44096147164120747

In [171]:
findall(>(0.3), x)

8-element Vector{Int64}:
  1
  2
  4
  6
  7
  8
  9
 10

In [172]:
findfirst(<(0.7), x)

1

In [173]:
findnext(x, 5) do v
    v ≤ 0.2 || v ≥ 0.8
end

6

In [174]:
b = BitVector([0, 0, 1, 0, 1]);

In [175]:
findall(b)

2-element Vector{Int64}:
 3
 5

In [176]:
findlast(b)

5

In [177]:
findprev(b, 4)

3

In [178]:
M = [3 1 4; 5 9 2];

In [179]:
findall(isodd, M)

4-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(1, 2)
 CartesianIndex(2, 2)

##### コード3-30. `argmax()`、`argmin()`、`findmax`、`findmin` の例(1)

In [180]:
M = [3 1 4; 5 9 2];

In [181]:
argmax(M)

CartesianIndex(2, 2)

In [182]:
argmin(M)

CartesianIndex(1, 2)

In [183]:
findmax(M)

(9, CartesianIndex(2, 2))

In [184]:
findmin(M)

(1, CartesianIndex(1, 2))

In [185]:
argmax(M, dims=1)

1×3 Matrix{CartesianIndex{2}}:
 CartesianIndex(2, 1)  CartesianIndex(2, 2)  CartesianIndex(1, 3)

In [186]:
argmin(M, dims=2)

2×1 Matrix{CartesianIndex{2}}:
 CartesianIndex(1, 2)
 CartesianIndex(2, 3)

In [187]:
findmax(M, dims=1)

([5 9 4], CartesianIndex{2}[CartesianIndex(2, 1) CartesianIndex(2, 2) CartesianIndex(1, 3)])

In [188]:
findmin(M, dims=2)

([1; 2;;], CartesianIndex{2}[CartesianIndex(1, 2); CartesianIndex(2, 3);;])

#### 辞書関連関数

##### コード3-31. 辞書関連関数(1)

In [189]:
D = Dict(:a=>1, :b=>2, :c=>3)

Dict{Symbol, Int64} with 3 entries:
  :a => 1
  :b => 2
  :c => 3

In [190]:
keytype(D)

Symbol

In [191]:
valtype(D)

Int64

In [192]:
keys(D)

KeySet for a Dict{Symbol, Int64} with 3 entries. Keys:
  :a
  :b
  :c

In [193]:
collect(values(D))

3-element Vector{Int64}:
 1
 2
 3

In [194]:
keytype(D) === eltype(keys(D))

true

In [195]:
valtype(D) === eltype(values(D))

true

##### コード3-32. 辞書関連関数(2)：`haskey(D, k)`（`k ∈ keys(D)`）

In [196]:
D = Dict(:a=>1, :b=>2, :c=>3);

In [197]:
haskey(D, :a)  # `:a ∈ keys(D)` と書いても同じ

true

In [198]:
haskey(D, :no)  # `:no ∈ keys(D)` と書いても同じ

false

##### コード3-33. 辞書関連関数(3)：キー参照関連

In [199]:
D = Dict(:a=>1, :b=>2, :c=>3);

In [200]:
D[:a]

1

In [201]:
D[:d]

LoadError: KeyError: key :d not found

In [202]:
get(D, :a, -99)

1

In [203]:
get(D, :d, -99)

-99

In [204]:
get(D, :a) do
    println("ここには来ない！")
end

1

In [205]:
get(D, :d) do
    rand(-99:-90)  # 実行する度に結果が変わる
end

-99

In [206]:
get!(D, :d, 4)  # `D[:d] = 4` も実行される

4

In [207]:
D[:d]

4

In [208]:
get!(D, :e) do
    rand(-99:-90)  # 実行する度に結果が変わる
end

-94

In [209]:
D[:e]

-94

In [210]:
getkey(D, :e, :exists)  # ↑で登録されたので存在する

:e

In [211]:
getkey(D, :f, :notexists)

:notexists

##### コード3-34. 辞書関連関数(4)：登録・更新関連

In [212]:
D = Dict(:a=>1, :b=>2, :c=>3)

Dict{Symbol, Int64} with 3 entries:
  :a => 1
  :b => 2
  :c => 3

In [213]:
D[:a] = 10  # 更新

10

In [214]:
D

Dict{Symbol, Int64} with 3 entries:
  :a => 10
  :b => 2
  :c => 3

In [215]:
push!(D, :b=>4, :d=>5, :e=>6)  # `:b` は更新、`:d`, `:e` は新規登録

Dict{Symbol, Int64} with 5 entries:
  :a => 10
  :b => 4
  :d => 5
  :e => 6
  :c => 3

In [216]:
D

Dict{Symbol, Int64} with 5 entries:
  :a => 10
  :b => 4
  :d => 5
  :e => 6
  :c => 3

##### コード3-35. 辞書関連関数(5)：削除（取り出し）関連

In [217]:
D = Dict(:a=>1, :b=>2, :c=>3, :d=>4, :e=>-95);

In [218]:
delete!(D, :e)

Dict{Symbol, Int64} with 4 entries:
  :a => 1
  :b => 2
  :d => 4
  :c => 3

In [219]:
haskey(D, :e)

false

In [220]:
delete!(D, :e)  # エラーにならない

Dict{Symbol, Int64} with 4 entries:
  :a => 1
  :b => 2
  :d => 4
  :c => 3

In [221]:
pop!(D, :d)

4

In [222]:
haskey(D, :d)

false

In [223]:
pop!(D, :d)  # エラーになる

LoadError: KeyError: key :d not found

In [224]:
pop!(D, :d, -99)  # エラーにならない

-99

##### コード3-36. 辞書関連関数(6)：辞書のマージ

In [225]:
D1 = Dict(:a=>1, :b=>2, :c=>3);

In [226]:
D2 = Dict(:b=>4, :d=>5, :f=>6);

In [227]:
merge(D1, D2)

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 4
  :f => 6
  :d => 5
  :c => 3

In [228]:
merge(D2, D1)

Dict{Symbol, Int64} with 5 entries:
  :f => 6
  :b => 2
  :a => 1
  :d => 5
  :c => 3

In [229]:
mergewith(+, D1, D2)

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 6
  :f => 6
  :d => 5
  :c => 3

In [230]:
mergewith(D1, D2) do a, b
    10a + b
end

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 24
  :f => 6
  :d => 5
  :c => 3

In [231]:
merge!(D1, D2)  # D1 が更新される

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 4
  :f => 6
  :d => 5
  :c => 3

In [232]:
mergewith!(-, D1, D2)  # D1 が更新される

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 0
  :f => 0
  :d => 0
  :c => 3

In [233]:
D1

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 0
  :f => 0
  :d => 0
  :c => 3

#### 集合関連関数・演算子

##### コード3-37. 集合関連関数(1)：積集合・和集合

In [234]:
S1 = Set([1, 2, 3]); S2 = Set([2, 4, 6]);

In [235]:
S1 ∩ S2

Set{Int64} with 1 element:
  2

In [236]:
S1 ∪ S2

Set{Int64} with 5 elements:
  4
  6
  2
  3
  1

In [237]:
S0 = Set(1:10);

In [238]:
intersect!(S0, S1, S2)  # S0 が更新される

Set{Int64} with 1 element:
  2

In [239]:
S0

Set{Int64} with 1 element:
  2

In [240]:
union!(S0, S1, S2)  # S0 が更新される

Set{Int64} with 5 elements:
  4
  6
  2
  3
  1

In [241]:
S0

Set{Int64} with 5 elements:
  4
  6
  2
  3
  1

##### コード3-38. 集合関連関数(2)：差集合・対称差集合

In [242]:
S1 = Set([1, 2, 3]); S2 = Set([2, 4, 6]);

In [243]:
setdiff(S1, S2)

Set{Int64} with 2 elements:
  3
  1

In [244]:
setdiff(S2, S1)

Set{Int64} with 2 elements:
  4
  6

In [245]:
S0 = Set(1:10);

In [246]:
setdiff!(S0, S1, S2)  # S0 が更新される

Set{Int64} with 5 elements:
  5
  7
  10
  9
  8

In [247]:
S0

Set{Int64} with 5 elements:
  5
  7
  10
  9
  8

In [248]:
symdiff(S1, S2)

Set{Int64} with 4 elements:
  4
  6
  3
  1

In [249]:
symdiff(S2, S1)

Set{Int64} with 4 elements:
  4
  6
  3
  1

In [250]:
S0 = Set(1:10);

In [251]:
symdiff!(S0, S1, S2)  # S0 が更新される

Set{Int64} with 6 elements:
  5
  7
  2
  10
  9
  8

In [252]:
S0

Set{Int64} with 6 elements:
  5
  7
  2
  10
  9
  8

##### コード3-39. 集合関連関数(3)：追加・削除（取り出し）

In [253]:
S = Set(Int[])

Set{Int64}()

In [254]:
push!(S, 1, 2, 3)

Set{Int64} with 3 elements:
  2
  3
  1

In [255]:
delete!(S, 3)

Set{Int64} with 2 elements:
  2
  1

In [256]:
delete!(S, 4)  # 存在しない要素を指定してもエラーにならない

Set{Int64} with 2 elements:
  2
  1

In [257]:
pop!(S, 2)

2

In [258]:
pop!(S, 2)  # エラーになる

LoadError: KeyError: key 2 not found

In [259]:
pop!(S, 2, -99)

-99

#### タプル・名前付きタプル関連関数

##### コード3-40. タプル関連関数、名前付きタプル関連関数(1)

In [260]:
t = ('a', 2, 99.9, π);

In [261]:
first(t)

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [262]:
last(t)

π = 3.1415926535897...

In [263]:
Base.front(t)

('a', 2, 99.9)

In [264]:
Base.tail(t)

(2, 99.9, π)

In [265]:
nt = (a=1, b=2, c=3);

In [266]:
first(nt)

1

In [267]:
last(nt)

3

In [268]:
Base.front(nt)

(a = 1, b = 2)

In [269]:
Base.tail(nt)

(b = 2, c = 3)

##### コード3-41. 名前付きタプル関連関数(2)

In [270]:
nt = (c='a', i=2, f=99.9, π);

In [271]:
keys(nt)

(:c, :i, :f, :π)

In [272]:
values(nt)

('a', 2, 99.9, π)

In [273]:
haskey(nt, :a)

false

In [274]:
haskey(nt, 3)

true

In [275]:
get(nt, :c, 'X')

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [276]:
get(nt, 99, "デフォルト値")

"デフォルト値"

In [277]:
get(nt, :x) do
    rand()
end

0.7517496634926447

In [278]:
s = "あいう"

"あいう"

In [279]:
merge(nt, (a=1, b=2, s))

(c = 'a', i = 2, f = 99.9, π = π, a = 1, b = 2, s = "あいう")

In [280]:
merge(nt, [:a=>1, :b=>2, :c=>3, :d=>4, :e=>5])

(c = 3, i = 2, f = 99.9, π = π, a = 1, b = 2, d = 4, e = 5)

### 3-1-9. その他「あると便利」がある関数

### 3-1-10. 演算子は関数

#### コード3-42. `+` 演算子の関数としての利用例

In [281]:
+(1)  # == `+1`

1

In [282]:
+(1, 2)  # == `1 + 2`

3

In [283]:
+(1, 2, 3)  # == `1 + 2 + 3`

6

In [284]:
+(1, 2, 3, 4)  # == `1 + 2 + 3 + 4`

10

In [285]:
+(1, 2, 3, 4 ,5)  # == `1 + 2 + 3 + 4 + 5`

15

#### コード3-43. `÷` 演算子の関数としての利用例（再）

In [286]:
÷(5, 2)

2

In [287]:
÷(5, 2, RoundDown)

2

In [288]:
÷(5, 2, RoundUp)

3

In [289]:
÷(5, 2, RoundNearest)

2

In [290]:
÷(5, 2, RoundNearestTiesUp)

3

#### コード3-44. `≈` 演算子のヘルプ

In [291]:
?≈

"≈" can be typed by \approx<tab>

search: ≈



```
isapprox(x, y; atol::Real=0, rtol::Real=atol>0 ? 0 : √eps, nans::Bool=false[, norm::Function])
```

Inexact equality comparison. Two numbers compare equal if their relative distance *or* their absolute distance is within tolerance bounds: `isapprox` returns `true` if `norm(x-y) <= max(atol, rtol*max(norm(x), norm(y)))`. The default `atol` is zero and the default `rtol` depends on the types of `x` and `y`. The keyword argument `nans` determines whether or not NaN values are considered equal (defaults to false).

For real or complex floating-point values, if an `atol > 0` is not specified, `rtol` defaults to the square root of [`eps`](@ref) of the type of `x` or `y`, whichever is bigger (least precise). This corresponds to requiring equality of about half of the significant digits. Otherwise, e.g. for integer arguments or if an `atol > 0` is supplied, `rtol` defaults to zero.

The `norm` keyword defaults to `abs` for numeric `(x,y)` and to `LinearAlgebra.norm` for arrays (where an alternative `norm` choice is sometimes useful). When `x` and `y` are arrays, if `norm(x-y)` is not finite (i.e. `±Inf` or `NaN`), the comparison falls back to checking whether all elements of `x` and `y` are approximately equal component-wise.

The binary operator `≈` is equivalent to `isapprox` with the default arguments, and `x ≉ y` is equivalent to `!isapprox(x,y)`.

Note that `x ≈ 0` (i.e., comparing to zero with the default tolerances) is equivalent to `x == 0` since the default `atol` is `0`.  In such cases, you should either supply an appropriate `atol` (or use `norm(x) ≤ atol`) or rearrange your code (e.g. use `x ≈ y` rather than `x - y ≈ 0`).   It is not possible to pick a nonzero `atol` automatically because it depends on the overall scaling (the "units") of your problem: for example, in `x - y ≈ 0`, `atol=1e-9` is an absurdly small tolerance if `x` is the [radius of the Earth](https://en.wikipedia.org/wiki/Earth_radius) in meters, but an absurdly large tolerance if `x` is the [radius of a Hydrogen atom](https://en.wikipedia.org/wiki/Bohr_radius) in meters.

!!! compat "Julia 1.6"
    Passing the `norm` keyword argument when comparing numeric (non-array) arguments requires Julia 1.6 or later.


# Examples

```jldoctest
julia> isapprox(0.1, 0.15; atol=0.05)
true

julia> isapprox(0.1, 0.15; rtol=0.34)
true

julia> isapprox(0.1, 0.15; rtol=0.33)
false

julia> 0.1 + 1e-10 ≈ 0.1
true

julia> 1e-10 ≈ 0
false

julia> isapprox(1e-10, 0, atol=1e-8)
true

julia> isapprox([10.0^9, 1.0], [10.0^9, 2.0]) # using `norm`
true
```

---

```
isapprox(x; kwargs...) / ≈(x; kwargs...)
```

Create a function that compares its argument to `x` using `≈`, i.e. a function equivalent to `y -> y ≈ x`.

The keyword arguments supported here are the same as those in the 2-argument `isapprox`.

!!! compat "Julia 1.5"
    This method requires Julia 1.5 or later.



#### コード3-45. `≈` 演算子の関数としての利用例

In [292]:
v = 1.0e-10

1.0e-10

In [293]:
v ≈ 0.0

false

In [294]:
≈(v, 0.0, atol=1e-8)

true

#### コード3-46. 比較演算子で作る述語関数(1)：`∈` 演算子の使用例

In [295]:
is1to10 = ∈(1:10);

In [296]:
is1to10(3)

true

In [297]:
is1to10(12)

false

#### コード3-47. 比較演算子で作る述語関数(2)：`≈` 演算子の使用例

In [298]:
isalmost0 = ≈(0.0, atol=1e-8);

In [299]:
isalmost0(1.0e-10)

true